#!/bin/sh
HISTFILE="$ZDOTDIR/history"
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
# export PATH="/opt/anaconda/bin:$PATH"
export GOPATH=$HOME/.local/share/go
export ENHANCD_FILTER="/usr/bin/fzf:fzf:non-existing-filter"
export ENHANCD_COMMAND=ecd
export EDITOR="nvim"
export VISUAL="nvim"
export _Z_NO_RESOLVE_SYMLINKS=1
export QT_QPA_PLATFORMTHEME=qt5ct
export RANGER_LOAD_DEFAULT_RC=FALSE
export JDTLS_HOME=$HOME/.local/share/jdtls
export JDTLS_CONFIG=$HOME/.local/share/jdtls/config_linux

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#4f5f64"

