#!/bin/sh

# Zsh
alias zshrestart="source $ZDOTDIR/.zshrc"
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

alias clr="clear"

#color
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'

# Ls
alias ls='exa --color=always --group-directories-first --icons'           # my preferred listing
alias la='exa --git -la --color=always --group-directories-first --icons' # all files and dirs
alias ll='exa --git -l --color=always --group-directories-first --icons'  # long format
alias lt='exa -aT --color=always --group-directories-first --icons'       # tree listing
alias l.='exa -a | egrep "^\." --icons'

## Safety features
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
alias mkdir='mkdir -pv'
alias mkd='mkdir -pv'

# SSH
ssh() {
	if [[ $TERM == "xterm-kitty" ]]; then
		command kitty +kitten ssh $@
	else
		command ssh $@
	fi
}

# Xorg
alias s='startx'

# keyboard (never used them)
alias asdf='switch_layout'
alias aoeu='switch_layout'

# version control of dotfiles
alias config='/usr/bin/git --git-dir=$HOME/dotfiles --work-tree=$HOME'

# Suckles tools
alias suck="rm -f config.h && sudo make install"

# UiO
alias uiofs="sshfs -o reconnect,uid=1000,gid=1000,ServerAliveInterval=15,ServerAliveCountMax=3 suleymab@login.ifi.uio.no:privat $HOME/uio/mnt"
alias uioufs="fusermount -u $HOME/uio/mnt"
alias uiossh="ssh -t suleymab@login.ifi.uio.no \"cd ~/privat; zsh\""

# Neovim
alias nv="nvim"
nvim() {
	term=$(ps -p $(ps -p $$ -o ppid=) -o args=)
	if [[ $term == "nvim" ]]; then
		command nvr $@
	else
		command nvim $@
	fi
}

# Doom emacs
alias doom="~/.emacs.d/bin/doom"

# Tmux
alias t="tmux attach || tmux new-session"
alias ta='tmux attach -t'
alias tl="tmux ls"
tn() {
	if [[ -n $@ ]]; then
		command tmux new-session -s $@
	else
		command tmux new-session
	fi
}

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when gpg keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"
