#!/bin/sh
alias j='z'
alias f='zi'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# Example aliases
alias zshconfig="$EDITOR $ZDOTDIR/.zshrc"
alias zshrestart="source $ZDOTDIR/.zshrc"

alias clr="clear"

#color
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'

alias ls='exa --color=always --group-directories-first --icons' # my preferred listing
alias la='exa -la --color=always --group-directories-first --icons'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first --icons'  # long format
alias lt='exa -aT --color=always --group-directories-first --icons' # tree listing
alias l.='exa -a | egrep "^\." --icons'

#function man() {
	#LESS_TERMCAP_md=$'\e[01;31m' \
		#LESS_TERMCAP_me=$'\e[0m' \
		#LESS_TERMCAP_so=$'\e[01;44;33m' \
		#LESS_TERMCAP_se=$'\e[0m' \
		#LESS_TERMCAP_us=$'\e[01;32m' \
		#LESS_TERMCAP_ue=$'\e[0m' \
		#command man "$@"
	#}

alias mkdir='mkdir -p -v'

## Safety features
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'    
alias mkd='mkdir -pv'

alias s='startx'

#keyboard
alias asdf='switch_layout'
alias aoeu='switch_layout'

# version control of dotfiles
alias config='/usr/bin/git --git-dir=$HOME/dotfiles --work-tree=$HOME'

# Tmux
alias tl="tmux list-sessions"
#alias ta="tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --height=50% --reverse | xargs tmux switch-client -t"
#alias ta="tmux list-sessions | sed -E 's/\(.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
alias tn="tmux new -d"

alias suck="rm -f config.h && sudo make install"

# UIO
alias uiofs="sshfs -o reconnect,uid=1000,gid=984,ServerAliveInterval=15,ServerAliveCountMax=3 suleymab@login.ifi.uio.no:privat $HOME/uio"
alias uiossh="ssh -t suleymab@login.ifi.uio.no \"cd ~/privat; bash\""


