#!/bin/sh
HISTFILE="$ZDOTDIR/history"
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PARH="$HOME/.emacs.d/bin:$PATH"
export ENHANCD_FILTER="/usr/bin/fzf:fzf:non-existing-filter"
export ENHANCD_COMMAND=ecd
export EDITOR="nvim"
export VISUAL="nvim"
export _Z_NO_RESOLVE_SYMLINKS=1
export QT_QPA_PLATFORMTHEME=qt5ct
export RANGER_LOAD_DEFAULT_RC=FALSE
export JDTLS_HOME=$HOME/.local/share/jdtls
export JDTLS_CONFIG=$HOME/.local/share/jdtls/config_linux
export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
export XDG_CONFIG_HOME=$HOME/.config
export GTK_THEME=Adwaita:dark
export QT_STYLE_OVERRIDE=breeze:dark

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#4f5f64"

