#!/bin/sh

# some useful options (man zshoptions)
setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments
stty stop undef		# Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')

# beeping is annoying
unsetopt BEEP

ZSH_DISABLE_COMPFIX=true

# completions
autoload -Uz compinit
zstyle ':completion:*' menu select
# zstyle ':completion::complete:lsof:*' menu yes select
zmodload zsh/complist
# compinit
_comp_options+=(globdots)		# Include hidden files.

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Colors
autoload -Uz colors && colors

# Useful Functions
source "$ZDOTDIR/zsh-functions"

# Normal files to source
zsh_add_file "zsh-exports"
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-prompt"

# Plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "hlissner/zsh-autopair"
# zsh_add_plugin "zdharma-continuum/fast-syntax-highlighting"
if [[ $(ps -p $(ps -p $$ -o ppid=) -o args=) -ne "emacs" ]]
then
    zsh_add_plugin "jeffreytse/zsh-vi-mode" "c1480b4"
fi
zsh_add_plugin "rupa/z"

#. $ZDOTDIR/plugins/z/z.sh
# For more plugins: https://github.com/unixorn/awesome-zsh-plugins
# More completions https://github.com/zsh-users/zsh-completions

# bindkey "^p" up-line-or-beginning-search # Up
# bindkey "^n" down-line-or-beginning-search # Down
# bindkey "^k" up-line-or-beginning-search # Up
# bindkey "^j" down-line-or-beginning-search # Down

source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh
# export FZF_DEFAULT_COMMAND='rg --hidden -l ""'
compinit

# Edit line in vim with ctrl-e:
bindkey -v
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
# ZSH_HIGHLIGHT_STYLES[default]='fg=cyan' #base1
# ZSH_HIGHLIGHT_STYLES[alias]='fg=white'
# ZSH_HIGHLIGHT_STYLES[builtin]='fg=yellow'
# ZSH_HIGHLIGHT_STYLES[function]='fg=white'
# ZSH_HIGHLIGHT_STYLES[command]='fg=white'
# ZSH_HIGHLIGHT_STYLES[precommand]='fg=white'
# ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=green' #base01
# ZSH_HIGHLIGHT_STYLES[path]='fg=cyan'
# ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=blue' #base0
# ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=blue' #base0
# ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=red' #orange
