#!/bin/sh

# some useful options (man zshoptions)
setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments
stty stop undef		# Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')

setopt autolist
#unsetopt menucomplete

# beeping is annoying
unsetopt BEEP

ZSH_DISABLE_COMPFIX=true

# completions
#autoload -Uz compinit
#compinit
##zstyle ':completion:*' menu select
#zstyle ':completion:*:*:*:*:*' menu select
##zstyle ':completion::complete:lsof:*' menu yes select
#zmodload zsh/complist
## compinit
#_comp_options+=(globdots)		# Include hidden files.

source "$ZDOTDIR/completion"

autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^[[A" history-beginning-search-backward-end
bindkey "^[[B" history-beginning-search-forward-end

# Colors
autoload -Uz colors && colors

# Useful Functions
source "$ZDOTDIR/functions"

# Normal files to source
zsh_add_file "exports"
zsh_add_file "aliases"
zsh_add_file "prompt"

# Plugins
zsh_add_plugin "rupa/z"

source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh
# export FZF_DEFAULT_COMMAND='rg --hidden -l ""'
compinit

# Edit line in vim with ctrl-e:
bindkey -v
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

# can delete character and word after vi mode
bindkey "^?" backward-delete-char
bindkey "^w" backward-delete-word

# move cursor word by word (ctrl)
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
