#!/bin/sh
while read file; do
	case "$1" in
	"C-d")
		mv "$file" ~/.trash
		;;
	"C-r")
		convert -rotate 90 "$file" "$file"
		;;
	"C-c")
		echo -n "$file" | xclip -selection clipboard
		;;
	"C-w")
		~/bin/set-wall "$file" &&
			notify-send -u low -i "$HOME/.config/wall.png" "Wallpaper changed" ||
			notify-send -u low -i "$HOME/.config/wall.png" "Wallpaper could not be changed"
		;;
	"w")
		~/bin/set-wall "$file" &&
			notify-send -u low -i "$HOME/.config/wall.png" "Wallpaper changed" ||
			notify-send -u low -i "$HOME/.config/wall.png" "Wallpaper could not be changed"
		;;
	esac
done

# case "$1" in
# "C-x") xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
# "C-c") while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
# "C-e") while read file; do urxvt -bg "#444" -fg "#eee" -sl 0 -title "$file" -e sh -c "exiv2 pr -q -pa '$file' | less" & done ;;
# "C-g") tr '\n' '\0' | xargs -0 gimp & ;;
# "C-r") while read file; do rawtherapee "$file" & done ;;
# "C-comma") rotate 270 ;;
# "C-period") rotate 90 ;;
# "C-slash") rotate 180 ;;
# esac
