#!/bin/sh
WORKSPACE=`i3-msg -t get_workspaces \
  | jq '.[] | select(.focused==true).name' \
  | cut -d"\"" -f2`

~/.local/bin/i3l swap container with mark $WORKSPACE:main
#echo [ `i3-msg -t get_tree` ] | jq '.[]'
